services:
  - type: web
    name: dset-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: dset_database
      - key: CORS_ORIGINS
        value: "*"
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        value: ADMIN
      - key: ADMIN_PASSWORD
        sync: false
      - key: OPENAI_API_KEY
        sync: false
